### ISSUE TITLE
Table on your tour page

### ISSUE THREAD

**Issue by Pinestorm** [nep2ne/saas-website#2]
I'm on Chrome for Android.
I'm not sure if this is intentional or not, but your table on your tour page stretches out from the side of my screen, and I need to horizontally scroll to see all the content. When I scroll, your banner and your footer aren't stretched out all the way so it ends up looking cut off.

**Comment by nep2ne** [comment]
Thanks! That seems to be happening on all platforms. Looking for a fix now. :)
