### ISSUE TITLE
UC Browser iOS

### ISSUE THREAD

**Issue by jako-ry** [nep2ne/saas-website#3]
Hey, looks good overall but there are some margin issues with your navigation! The buttons overlap so I would add a bottom margin to fix that (to the about, tour, and partners buttons).

Also for your table on the tour page, I would give it the .block and .scrollable class so it doesn't extend your website to the right.

There is a spacing issue on your pricing page (the cards are all shifted to the left) which I'm assuming is due to a .push-r class, you might want to change that if you can.

**Comment by nep2ne** [comment]
Thank you!! Will look into all of those. :)
